# Exception generated outside try, should not be caught by catch.
# Terminates exceptionally.

x := 4;
y := 0-1;
z := 1000 / 0;
try
    x := x / (y+1)
catch
    x := 100
